[tool.poetry]
name = "movva_tools"
version = "1.3.0"
description = "Package that contains integrations and tools to use in issues of Movva organization."
authors = ["WillamesCampos <willwjccampos@gmail.com>"]
readme = "README.md"
packages = [{include = "movva_tools"}]

[tool.poetry.dependencies]
python = "^3.10"
google-api-python-client = "^2.95.0"
google-auth-httplib2 = "^0.1.0"
google-auth-oauthlib = "^1.0.0"
pandas = "^2.0.3"
rapidpro-python = "^2.12.0"
openpyxl = "^3.1.2"
loguru = "^0.7.0"
aiohttp = "^3.8.5"
more-itertools = "^10.0.0"
sqlalchemy = "^2.0.20"
psycopg2-binary = "^2.9.8"
google-cloud-secret-manager = "^2.16.4"
pytest = "^7.4.3"
flask = "^3.0.0"
marshmallow = "^3.20.1"


[tool.poetry.group.dev.dependencies]
validate-docbr = "^1.10.0"
faker = "^19.2.0"
pytest = "^7.4.0"
coverage = "^7.2.7"
flake8 = "^6.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
