[tool.coverage.run]
branch = true
source = [ "syntrac_opentelemetry/instrumentation/langchain" ]

[tool.coverage.report]
exclude_lines = [ "if TYPE_CHECKING:" ]
show_missing = true

[tool.poetry]
name = "syntrac-opentelemetry-instrumentation-langchain"
version = "0.0.3"
description = "OpenTelemetry Langchain instrumentation"
authors = [ "Vuong Ngo <vuongngo.pd@gmail.com>" ]
repository = "https://github.com/syntracAI/syntrac/tree/main/packages/python/opentelemetry-instrumentation-langchain"
license = "Apache-2.0"
readme = "README.md"

  [[tool.poetry.packages]]
  include = "syntrac_opentelemetry/instrumentation/langchain"

  [tool.poetry.dependencies]
  python = ">=3.9,<4"
  opentelemetry-api = "^1.23.0"
  opentelemetry-instrumentation = "0.44b0"
  opentelemetry-semantic-conventions = "0.44b0"
  syntrac-opentelemetry-semantic-conventions-ai = "0.0.1"

[tool.poetry.group.dev]
dependencies = { }

  [tool.poetry.extras]
  instruments = [ "langchain" ]

[tool.poetry.plugins.opentelemetry_instrumentor]
langchain = "syntrac_opentelemetry.instrumentation.langchain:LangchainInstrumentor"

[build-system]
requires = [ "poetry-core" ]
build-backend = "poetry.core.masonry.api"
