[project]
name = "ValeraLib"
version = "1.4.1"
description = "The library goes brrrrrr"
keywords = [
    "The greatest package to ever exist",
]
readme = "README.md"
authors = [
    { name = "Valera", email = "v79166789533@gmail.com" },
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
]
requires-python = ">=3.6"
dependencies = [
    "numpy>=1.24.3,<2.0.0",
    "pandas>=1.5.3,<2.0.0",
    "playsound>=1.2.2,<2.0.0",
    "plotly>=5.14.1,<6.0.0",
    "requests>=2.31.0,<3.0.0",
    "telebot",
]

[project.urls]
Homepage = "https://github.com/Valera6/ValeraLib"

[build-system]
requires = [
    "pdm-backend",
]
build-backend = "pdm.backend"

[tool.ruff]
line-length = 210
indent-width = 2
src = [
    "src",
    "test",
]
fixable = [
    "ALL",
]
unfixable = []
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
quote-style = "double"
indent-style = "tab"
docstring-code-format = false
skip-magic-trailing-comma = false

[tool.ruff.lint]
ignore = [
    "E713",
    "F403",
]
