[project]
name = 'plutobook'
version = '0.0.9'
description = 'Paged HTML rendering library'
readme = 'README.md'
requires-python = '>=3.8'
license = {file = 'LICENSE'}
authors = [
    {name = 'Samuel Ugochukwu', email = 'sammycageagle@gmail.com'},
]

[build-system]
build-backend = 'mesonpy'
requires = ['meson-python']
