[tool.poetry]
authors     = ["9FS <pray4spam@googlemail.com>"]
description = ""
license     = "MIT"
name        = "KFSconvert_to_SI"
packages    = [{ include = "KFSconvert_to_SI" }]
readme      = "readme.md"
repository  = "https://github.com/9-FS/2023-09-20-KFSconvert_to_SI"
version     = "1.0.2"

[tool.poetry.dependencies]
python = "^3.12.0"

[tool.poetry.group.dev.dependencies]
hypothesis = "^6.0.0"
kfslog     = "^2.0.0"
pytest     = "^8.0.0"

[build-system]
build-backend = "poetry.core.masonry.api"
requires      = ["poetry-core"]
