[tool.poetry]
name = "nexus-scraper"
version = "0.2.0"
description = ""
authors = ["Spoked <dreu.lavelle@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pydantic = "^2.7.1"
requests = "^2.31.0"
pydantic-settings = "^2.2.1"

[tool.poetry.urls]
repository = "https://github.com/dreulavelle/NexusScraper"

[tool.poetry.group.dev.dependencies]
pytest = "^8.2.0"
pytest-cov = "^5.0.0"
pyright = "^1.1.361"
isort = "^5.13.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.packages]]
include = "Nexus"