[build-system]
requires = ["setuptools>=61.0","pandas"]
build-backend = "setuptools.build_meta"

[project]
dependencies = [ "pandas"]
name = "Way2DSSAT"
version = "0.0.11"
authors = [
  { name="Manavjot", email="manavjotsingh97@gmail.com" },
]
description = "Package to handle input DSSAT files"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
keywords=['python','DSSAT', 'Input', 'gSSURGO']

[project.urls]
Homepage = "https://github.com/ManavjotSingh97/Way2DSSAT"
Issues = "https://github.com/ManavjotSingh97/Way2DSSAT/issues"