[tool.poetry]
name = "ce-mkc"
version = "0.0.1-a6"
description = "A command line utility to set up Kafka, MongoDB, and MongoDB Kafka Connector environments."
authors = ["Your Name <you@example.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.9"
certifi = "2023.7.22"
charset-normalizer = "3.2.0"
confluent-kafka = "2.2.0"
dnspython = "2.3.0"
docker = "6.1.3"
idna = "3.4"
packaging = "23.1"
pymongo = "4.5.0"
requests = ">=1.26.6"
urllib3 = "2.0.4"
websocket-client = "1.6.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
