[tool.poetry]
name = "octostar-streamlit-search-experience"
version = "0.1.2"
description = ""
authors = ["Your Name <you@example.com>"]
license = "MIT"
readme = "README.md"
include = [
    "octostar_streamlit_search_experience/frontend/dist/**/*",
]

[tool.poetry.dependencies]
python = ">=3.9,<3.9.7 || >3.9.7,<4.0"
streamlit = "^1.34.0"
streamlit-octostar-research = "^0.1.22"
pydantic = "^2.7.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
