[project]
name = "golink"
package = "golink"

# [build-system]
# requires = ["setuptools>=42", "wheel"]
# build-backend = "setuptools.build_meta"

entry-points = ["golink = golink.cli:main"]

# [project.scripts]
# golink = "golink.cli:main"


[tool.poetry]
name = "golink"
version = "0.5.4"
license = "GPLv3"
description = "A simple URL shortener"
authors = ["Max Vogel", "Logan Engstrom"]
readme = "README.md"
repository = "https://github.com/Mehvix/golink"

[tool.poetry.dependencies]
python = "^3.9"
tqdm = "^4.66.4"
tabulate = "^0.9.0"
requests = "^2.31.0"
pandas = "^2.2.2"

[tool.setuptools]
include-package-data = true
package-data = { "" = ["script.js", "style.css"] }
zip-safe = false
