[tool.poetry]
name = "pi-log"
version = "0.5.8.1"
description = "Project to add utility log functions for Python"
authors = ["parnell <3028114+parnell@users.noreply.github.com>"]
readme = "README.md"
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9,<4.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
