[build-system]
requires = [ "poetry-core>=1.0.0",]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "langevals"
version = "0.1.4"
description = "A platform to evaluate LLM outputs using various evaluators."
authors = [ "Rogerio Chaves <rogerio@langwatch.ai>",]
license = "MIT"
[[tool.poetry.source]]
name = "pytorch_cpu"
url = "https://download.pytorch.org/whl/cpu"
priority = "explicit"

[tool.poetry.dependencies]
pytest = "^8.1.2"
python = "^3.11"
fastapi = "^0.110.0"
hypercorn = "^0.16.0"
pydantic = "^2.6.4"
python-dotenv = "1.0.1"
mangum = "^0.17.0"
pandas = "^2.2.2"
langevals-core = "^0.1.3"
langevals-azure = "^0.1.3"
langevals-openai = "^0.1.3"
langevals-example = "^0.1.3"
langevals-ragas = "^0.1.3"
langevals-google_cloud = "^0.1.3"
langevals-custom = "^0.1.2"
langevals-lingua = "^0.1.2"
langevals-aws = "^0.1.2"
langevals-huggingface = "^0.1.2"
langevals-langevals = "^0.1.2"
[[tool.poetry.dependencies.torch]]
version = "^2.2.2"
optional = true
source = "pytorch_cpu"
markers = "sys_platform == 'linux'"

[[tool.poetry.dependencies.torch]]
version = "^2.2.2"
optional = true
source = "pypi"
markers = "sys_platform != 'linux'"

[tool.poetry.scripts]
langevals-server = "langevals.server:main"

[tool.poetry.dev-dependencies]
toml = "^0.10.2"
grevillea = "^0.0.1"
litellm = "^1.35.29"
instructor = "^1.2.2"
pytest-xdist = "^3.5.0"
flaky = "^3.8.1"

[tool.poetry.extras]
azure = [ "langevals-azure",]
openai = [ "langevals-openai",]
example = [ "langevals-example",]
ragas = [ "langevals-ragas",]
google_cloud = [ "langevals-google_cloud",]
custom = [ "langevals-custom",]
lingua = [ "langevals-lingua",]
aws = [ "langevals-aws",]
huggingface = [ "langevals-huggingface",]
langevals = [ "langevals-langevals",]
all = [ "langevals-azure", "langevals-langevals", "langevals-example", "langevals-lingua", "langevals-ragas", "langevals-google_cloud", "langevals-aws", "langevals-huggingface", "langevals-custom", "langevals-openai",]

[tool.poetry.plugins.pytest11]
pass_rate_plugin = "langevals.pytest_plugins.pass_rate_plugin"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.4"
