[tool.poetry]
name = "pms-model-manager"
version = "1.3.0"
description = "lib for pms"
authors = ["HyeongSeok Kim <tiryul@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
mlflow = "2.11.1"
onnx = "^1.15.0"
pytz = "^2024.1"
loguru = "^0.7.2"
boto3 = "^1.34.66"
typer = "^0.9.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.1.1"
pytest-order = "^1.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
pmm = "pms_model_manager._cli:main"
