[build-system]
requires = [ "poetry-core>=1.0.0",]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "langevals-huggingface"
version = "0.1.2"
description = "LangEvals huggingface evaluators."
authors = [ "Yevhenii Budnyk <y.budnyk789@gmail.com>",]
license = "MIT"
[[tool.poetry.source]]
name = "pytorch_cpu"
url = "https://download.pytorch.org/whl/cpu"
priority = "explicit"

[tool.poetry.dependencies]
python = "^3.11"
langevals-core = "^0.1.3"
evaluate = "^0.4.1"
bert-score = "^0.3.13"
[[tool.poetry.dependencies.torch]]
version = "^2.2.2"
source = "pytorch_cpu"
markers = "sys_platform == 'linux'"

[[tool.poetry.dependencies.torch]]
version = "^2.2.2"
source = "pypi"
markers = "sys_platform != 'linux'"

[tool.poetry.group.test.dependencies]
pytest = "^7.4.2"
python-dotenv = "1.0.1"
